global:
  name: Interactive Mobility Landscape
  short_name: IML
  mode: CNCF
  repo: cncf/mobility_landscape
  website: 'https://nrel.github.io/mobility_landscape/'
  company_url: 'https://www.nrel.gov/index.html'
  email: k.shankari@nrel.gov
  meta:
    title: Interactive Mobility Landscape
    fb_admin: alex.contini.94
    description: 'Filter and sort by GitHub stars, funding, commits, contributors, hq location, and tweets'
    twitter: '@CloudNativeFdn'
    google_site_verification: 8l35EQriJXntsib5sBdRu4gmDV1nAP9PSoHccJC8ABQ
    ms_validate: 3AF9FFA12CCC3C49C0ABA71CCA222665
  flags:
    hide_license_for_categories:
      - Special
      - Members
    hide_category_from_subcategories:
      - End User Supporter
twitter:
  search: landscape.cncf.io
  url: 'https://landscape.cncf.io'
  text: Cloud Native Landscape from @CloudNativefdn
relation:
  label: CNCF Relation
  url: cncf
  values:
    - id: hosted
      label: CNCF Projects
      children:
        - id: graduated
          label: CNCF Graduated Projects
          prefix: CNCF
          tag: Graduated Project
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: CNCF Graduated
          big_picture_color: 'rgb(24,54,114)'
        - id: incubating
          label: CNCF Incubating Projects
          prefix: CNCF
          tag: Incubating Project
          color: '#00cbff'
          big_picture_order: 2
          big_picture_label: CNCF Incubating
          big_picture_color: 'rgb(83, 113, 189)'
        - id: sandbox
          label: CNCF Sandbox Projects
          prefix: CNCF
          tag: Sandbox Project
          color: '#d1f7ff'
          big_picture_label: CNCF Sandbox
          big_picture_color: 'rgb(108, 165, 209)'
          additional_relation: member
    - id: member
      label: Mobility Data Landscape Projects
      tag: CNCF Member
    - id: false
      label: Non-CNCF Member Products/Projects
      url: 'no'
membership:
  Platinum:
    name: CNCF
    label: Platinum Member
    end_user_label: Platinum End User Member
    funding: Platinum
    is_large: true
  Gold:
    name: CNCF
    label: Gold Member
    end_user_label: Gold End User Member
    funding: Gold
    is_large: true
  Silver:
    name: CNCF
    label: Silver Member
    end_user_label: Silver End User Member
    funding: Silver
  Academic:
    name: CNCF
    label: Academic Member
    end_user_label: Academic End User Member
    funding: Academic
  Nonprofit:
    name: CNCF
    label: Nonprofit Member
    end_user_label: Nonprofit End User Member
    funding: Nonprofit
  End User Supporter:
    name: CNCF
    label: End User Supporter
    funding: End User Supporter
    enduser: true
  linux_foundation:
    name: LF
    label: Project
    funding: Linux Foundation
    crunchbase_and_children: 'https://www.crunchbase.com/organization/linux-foundation'
  cncf:
    name: CNCF
    label: Project
    funding: CNCF
  'false':
    funding: 'No'
home:
  header: >
    <h1>Interactive Mobility Data Landscape</h1> The Interactive Mobility Landscape is made to capture the current state of mobility specifications.
    This landscape does not capture the specifications for areas such as physical Infrastructure or other standards with regard to construction (ie will not include standards on road roughness but data on how potholes are reported) but instead on specifications for data related to mobility.
    The interactive mobility landscape (<a target="_blank" href="images/landscape.png">png</a>, <a target="_blank" href="images/landscape.pdf">pdf</a>),
    and serverless landscape (<a target="_blank" href="images/serverless.png">png</a>, <a target="_blank" href="images/serverless.pdf">pdf</a>) are dynamically generated below.
  footer: |
    Crunchbase data is used under license from Crunchbase to CNCF.
ads:
  - url: 'https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/?utm_source=cncf_landscape&utm_medium=web&utm_campaign=kccncna20'
    image: /images/info1.jpg
    title: KubeCon + CloudNativeCon North America 2020
presets:
  - url: /format=card-mode&grouping=no&license=open-source&sort=first-commit
    label: Cards by age
  - url: /license=open-source
    label: Open source landscape
  - url: /category=cncf-members&format=card-mode&grouping=category
    label: Member cards
  - url: /format=card-mode&grouping=no&sort=stars
    label: Cards by stars
  - url: '/format=card-mode&grouping=headquarters&headquarters=china,hong-kong,taiwan'
    label: Cards from China
  - url: '/format=card-mode&grouping=category&category=certified-kubernetes-distribution,certified-kubernetes-hosted,certified-kubernetes-installer,special'
    label: Certified K8s/KCSP/KTP
  - url: /format=card-mode&grouping=no&sort=amount
    label: Cards by MCap/Funding
big_picture:
  main:
    tab_index: -1
    url: landscape
    name: Landscape
    short_name: Land...
    title: Interactive Mobility Landscape
    fullscreen_header: Missing data or request a change?  Submit a pull request!
    elements:
      - type: HorizontalCategory
        category: Data Collection Method
        rows: 6
        width: 1000
        height: 100
        top: 0
        left: 0
        color: 'rgb(107,61,46)'
      - type: HorizontalCategory
        category: Data
        rows: 6
        width: 1000
        height: 400
        top: 125
        left: 0
        color: 'rgb(107,61,46)'
      - type: HorizontalCategory
        category: Data Formatting
        rows: 6
        width: 1000
        height: 100
        top: 550
        left: 0
        color: 'rgb(107,61,46)'
      - type: VerticalCategory
        category: Tools
        cols: 9
        width: 275
        height: 1500
        top: 700
        left: 0
        color: 'rgb(109,61,143)'
      - type: VerticalCategory
        category: Simulations
        cols: 9
        width: 275
        height: 1000
        top: 700
        left: 350
        color: 'rgb(46,107,46)'
      - type: LandscapeInfo
        width: 295
        height: 260
        top: 700
        left: 700
        children:
          - type: text
            text: >
              This landscape is intended as a map through the previously uncharted terrain of mobility data. The hope is that this space
              can be used for collaboration among mobility data researchers and creators.
            top: 80
            left: 120
            right: 20
            font_size: 11
          - type: image
            image: qr-code.svg
            top: 80
            left: 15
            width: 90
            height: 90
            title: QR Code
          - type: title
            title: NREL
            top: 168
            left: 18
            font_size: 23
          - type: image
            image: imdl_logo.svg
            width: 140
            left: 15
            top: 15
            title: Landscape Logo
test:
  header: Interactive Mobility Data Landscape
  section: Landscape Projects
  logo: tom-tom.svg
anonymous_organization:
  name: Non-Public Unnamed Organization
  homepage: 'https://nrel.github.io/mobility_landscape/'
  city: Bouvet Island
  region: Antarctica
  country: Antarctica
  twitter: 'https://twitter.com/CloudNativeFdn'
mosaics:
  - imdl_logo.svg
  - nrel_logo.svg
