global:
  name: Interactive Mobility Landscape
  short_name: IML
  mode: CNCF
  repo: cncf/mobility_landscape
  website: 'https://landscape.cncf.io'
  short_domain: l.cncf.io
  company_url: 'https://www.cncf.io'
  email: info@cncf.io
  self: 'https://www.crunchbase.com/organization/cloud-native-computing-foundation'
  slack_channel: T08PSQ7BQ/BC07DVB0C/jqc0ANnvpVddAp651jgyMKdr
  meta:
    title: Interactive Mobility Landscape
    fb_admin: alex.contini.94
    description: 'Filter and sort by GitHub stars, funding, commits, contributors, hq location, and tweets'
    twitter: '@CloudNativeFdn'
    google_site_verification: 8l35EQriJXntsib5sBdRu4gmDV1nAP9PSoHccJC8ABQ
    ms_validate: 3AF9FFA12CCC3C49C0ABA71CCA222665
  flags:
    hide_license_for_categories:
      - Special
      - CNCF Members
    hide_category_from_subcategories:
      - End User Supporter
twitter:
  search: landscape.cncf.io
  url: 'https://landscape.cncf.io'
  text: Cloud Native Landscape from @CloudNativefdn
relation:
  label: CNCF Relation
  url: cncf
  values:
    - id: hosted
      label: CNCF Projects
      children:
        - id: graduated
          label: CNCF Graduated Projects
          prefix: CNCF
          tag: Graduated Project
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: CNCF Graduated
          big_picture_color: 'rgb(24,54,114)'
        - id: incubating
          label: CNCF Incubating Projects
          prefix: CNCF
          tag: Incubating Project
          color: '#00cbff'
          big_picture_order: 2
          big_picture_label: CNCF Incubating
          big_picture_color: 'rgb(83, 113, 189)'
        - id: sandbox
          label: CNCF Sandbox Projects
          prefix: CNCF
          tag: Sandbox Project
          color: '#d1f7ff'
          big_picture_label: CNCF Sandbox
          big_picture_color: 'rgb(108, 165, 209)'
          additional_relation: member
    - id: member
      label: CNCF Member Products/Projects
      tag: CNCF Member
    - id: false
      label: Non-CNCF Member Products/Projects
      url: 'no'
membership:
  Platinum:
    name: CNCF
    label: Platinum Member
    end_user_label: Platinum End User Member
    funding: Platinum
    is_large: true
  Gold:
    name: CNCF
    label: Gold Member
    end_user_label: Gold End User Member
    funding: Gold
    is_large: true
  Silver:
    name: CNCF
    label: Silver Member
    end_user_label: Silver End User Member
    funding: Silver
  Academic:
    name: CNCF
    label: Academic Member
    end_user_label: Academic End User Member
    funding: Academic
  Nonprofit:
    name: CNCF
    label: Nonprofit Member
    end_user_label: Nonprofit End User Member
    funding: Nonprofit
  End User Supporter:
    name: CNCF
    label: End User Supporter
    funding: End User Supporter
    enduser: true
  linux_foundation:
    name: LF
    label: Project
    funding: Linux Foundation
    crunchbase_and_children: 'https://www.crunchbase.com/organization/linux-foundation'
  cncf:
    name: CNCF
    label: Project
    funding: CNCF
  'false':
    funding: 'No'
home:
  header: >
    <h1>Interactive Mobility Specifications Landscape</h1> The Interactive Mobility Landscape is made to capture the current state of mobility specifications.
    This landscape does not capture the specifications for areas such as physical infastructure or other standards with regard to construction (ie will not include standards on road roughness but data on how potholes are reported) but instead on specifications for data related to mobility.
    The interactive mobility landscape (<a target="_blank" href="images/landscape.png">png</a>, <a target="_blank" href="images/landscape.pdf">pdf</a>),
    and serverless landscape (<a target="_blank" href="images/serverless.png">png</a>, <a target="_blank" href="images/serverless.pdf">pdf</a>) are dynamically generated below.
  footer: |
    Crunchbase data is used under license from Crunchbase to CNCF.
ads:
  - url: 'https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/?utm_source=cncf_landscape&utm_medium=web&utm_campaign=kccncna20'
    image: /images/info1.jpg
    title: KubeCon + CloudNativeCon North America 2020
presets:
  - url: /format=card-mode&grouping=no&license=open-source&sort=first-commit
    label: Cards by age
  - url: /license=open-source
    label: Open source landscape
  - url: /category=cncf-members&format=card-mode&grouping=category
    label: Member cards
  - url: /format=card-mode&grouping=no&sort=stars
    label: Cards by stars
  - url: '/format=card-mode&grouping=headquarters&headquarters=china,hong-kong,taiwan'
    label: Cards from China
  - url: '/format=card-mode&grouping=category&category=certified-kubernetes-distribution,certified-kubernetes-hosted,certified-kubernetes-installer,special'
    label: Certified K8s/KCSP/KTP
  - url: /format=card-mode&grouping=no&sort=amount
    label: Cards by MCap/Funding
big_picture:
  main:
    tab_index: -1
    url: landscape
    name: Landscape
    short_name: Land...
    title: Interactive Mobility Landscape
    fullscreen_header: Overwhelmed? Please see the CNCF Trail Map. That and the interactive landscape are at l.cncf.io
    elements:
      - type: HorizontalCategory
        category: Infastructure
        rows: 6
        width: 1050
        height: 270
        top: 0
        left: 0
        color: 'rgb(109,61,143)'
      - type: HorizontalCategory
        category: Vehicles
        rows: 6
        width: 1050
        height: 270
        top: 285
        left: 0
        color: 'rgb(46,107,46)'
      - type: HorizontalCategory
        category: People
        rows: 4
        width: 950
        height: 270
        top: 575
        left: 0
        color: 'rgb(143,88,61)'
      - type: HorizontalCategory
        category: Infastructure-Vehicles
        rows: 6
        width: 1000
        height: 150
        top: 850
        left: 0
        color: 'rgb(46,97,107)'
      - type: HorizontalCategory
        category: Infastructure-People
        rows: 6
        width: 1000
        height: 270
        top: 1010
        left: 0
        color: 'rgb(107,97,46)'
      - type: HorizontalCategory
        category: Vehicles-People
        rows: 6
        width: 1000
        height: 150
        top: 1300
        left: 0
        color: 'rgb(107,97,46)'
      - type: VerticalCategory
        category: Infastructure-Vehicles-People
        cols: 9
        width: 315
        height: 1000
        top: 0
        left: 1100
        color: 'rgb(107,61,46)'
      - type: LandscapeInfo
        width: 295
        height: 260
        top: 1450
        left: 0
        children:
          - type: text
            text: >
              This landscape is intended as a map through the previously uncharted terrain of cloud native technologies. There are many routes to deploying a
              cloud native application, with CNCF Projects representing a particularly well-traveled path.
            top: 80
            left: 120
            right: 20
            font_size: 11
          - type: image
            image: qr-l.svg
            top: 80
            left: 15
            width: 90
            height: 90
            title: QR Code
          - type: title
            title: l.cncf.io
            top: 168
            left: 18
            font_size: 23
          - type: image
            image: right-logo.svg
            width: 109
            right: 15
            top: 15
            title: CNCF Logo
          - type: image
            image: left-logo.svg
            width: 140
            left: 15
            top: 15
            title: Landscape Logo
          - type: image
            image: amplify.svg
            width: 50
            right: 15
            top: 40
            title: Amplify Logo
          - type: image
            image: redpoint.svg
            width: 50
            right: 75
            top: 42
            title: Redpoint Logo
  extra:
    tab_index: 1
    url: serverless
    name: Serverless
    short_name: Server...
    title: CNCF Serverless Landscape
    fullscreen_header: See the serverless interactive display at s.cncf.io
    elements:
      - type: HorizontalCategory
        category: Tools
        rows: 1
        width: 570
        height: 90
        top: 0
        left: 0
        color: 'rgb(143,109,61)'
        fit_width: true
      - type: HorizontalCategory
        category: Framework
        rows: 1
        width: 820
        height: 90
        top: 100
        left: 0
        fit_width: true
        offset: 10
        color: 'rgb(102,61,143)'
      - type: HorizontalCategory
        category: Security
        rows: 1
        width: 240
        height: 90
        top: 0
        left: 580
        color: 'rgb(179,94,77)'
        fit_width: true
        offset: 40
      - type: HorizontalCategory
        category: Hosted Platform
        rows: 2
        width: 480
        height: 120
        top: 200
        left: 0
        fit_width: true
        color: 'rgb(83,115,38)'
      - type: HorizontalCategory
        category: Installable Platform
        rows: 2
        width: 330
        height: 120
        top: 200
        left: 490
        fit_width: true
        color: 'rgb(83,115,38)'
      - type: LandscapeInfo
        width: 520
        height: 120
        top: 330
        left: 0
        children:
          - type: text
            text: >
              Serverless computing refers to a new model of cloud native computing, enabled by architectures that do not require server management to build and
              run applications. This landscape illustrates a finer-grained deployment model where applications, bundled as one or more functions, are uploaded
              to a platform and then executed, scaled, and billed in response to the exact demand needed at the moment
            top: 10
            left: 90
            right: 150
            font_size: 9
          - type: image
            image: qr-s.svg
            top: 10
            left: 5
            width: 70
            height: 70
            title: QR Code
          - type: title
            title: s.cncf.io
            top: 75
            left: 10
            font_size: 16
          - type: image
            image: left-logo.svg
            width: 110
            right: 15
            top: 10
            title: Landscape Logo
          - type: image
            image: right-logo.svg
            width: 109
            right: 15
            top: 45
            title: CNCF Logo
          - type: image
            image: redpoint.svg
            width: 109
            right: 15
            top: 70
            title: Redpoint Logo
      - type: LandscapeLink
        url: landscape
        title: Cloud Native Landscape
        layout: subcategory
        left: 635
        top: 325
        width: 185
        height: 125
        color: 'rgb(118, 181, 237)'
  third:
    tab_index: 2
    url: members
    name: Members
    title: CNCF Members
    fullscreen_header: Become a CNCF member at cncf.io/join or view the interactive member landscape at m.cncf.io
    fullscreen_hide_grey_logos: true
    elements:
      - type: HorizontalCategory
        category: Platinum
        rows: 4
        width: 1250
        height: 200
        top: 0
        left: 0
        color: '#c5c4c2'
        fit_width: true
        offset: 60
      - type: HorizontalCategory
        category: Gold
        rows: 4
        width: 1250
        height: 200
        top: 200
        left: 0
        color: '#D4AF37'
        fit_width: true
        offset: 70
      - type: HorizontalCategory
        category: Silver
        rows: 23
        width: 1250
        height: 770
        top: 400
        left: 0
        color: '#909090'
        fit_width: true
      - type: HorizontalCategory
        category: End User Supporter
        rows: 15
        width: 300
        height: 520
        top: 0
        left: 1280
        color: 'rgb(38,115,57)'
        fit_width: true
        offset: 40
      - type: HorizontalCategory
        category: Nonprofit
        rows: 4
        width: 300
        height: 170
        top: 525
        left: 1280
        color: 'rgb(143,61,122)'
        fit_width: true
        offset: 0
      - type: HorizontalCategory
        category: Academic
        rows: 1
        width: 300
        height: 80
        top: 700
        left: 1280
        color: 'rgb(115,83,38)'
        fit_width: true
        offset: 0
      - type: LandscapeLink
        url: landscape
        title: Landscape
        layout: category
        left: 1280
        top: 795
        width: 300
        height: 180
        color: 'rgb(64,117,191)'
      - type: LandscapeInfo
        width: 300
        height: 200
        top: 970
        left: 1280
        children:
          - type: text
            text: >
              CNCF has over 500 members including the worldâ€™s largest public cloud and enterprise software companies as well over two hundred innovative
              startups. Join your industry peers in helping build and shape the cloud native ecosystem.
            top: 15
            left: 100
            right: 15
            font_size: 11
          - type: image
            image: qr-l.svg
            top: 15
            left: 5
            width: 90
            height: 90
            title: QR Code
          - type: title
            title: m.cncf.io
            top: 105
            left: 5
            font_size: 21
          - type: image
            image: left-logo.svg
            left: 4
            height: 30
            bottom: 13
            width: 116
            title: Landscape Logo
          - type: image
            image: right-logo.svg
            left: 127
            height: 30
            bottom: 13
            width: 161
            title: CNCF Logo
    category: CNCF Members
test:
  header: Interactive Mobility Landscape
  section: CNCF Graduated Projects
  logo: kubernetes.svg
anonymous_organization:
  name: Non-Public Unnamed Organization
  homepage: 'https://www.cncf.io'
  city: Bouvet Island
  region: Antarctica
  country: Antarctica
  twitter: 'https://twitter.com/CloudNativeFdn'
mosaics:
  - cncf-logo.svg
  - landscape-logo.svg
